/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LABEL = 3;
  /** RegularExpression Id. */
  int EOL = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<LABEL>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"EX\"",
    "\"AX\"",
    "\"EF\"",
    "\"AF\"",
    "\"EG\"",
    "\"AG\"",
    "\"E\"",
    "\"U\"",
    "\"A\"",
    "\"/\\\\\"",
    "\"\\\\/\"",
    "\"=>\"",
    "\"~\"",
    "\"TRUE\"",
  };

}
